### ISSUE TITLE
[Feature]: Add basic HMAC signing

### ISSUE THREAD

**Issue by thinkjrs** [musicfox/cryptography#9]
## Summarize your feature

Since we use CBC padding we need to sign each request to prevent possible timing attacks against the secret key. 

This should be done on both sides, Python and JavaScript.

#### Python
- `add_signature` function 
- `check_signature` function
- `encrypt` should sign the request using `add_signature`
- `decrypt` should check the request using `check_signature`

_From the python resource tagged in the references:_
```python
hmac_sha.py
import hmac
import hashlib

digest_maker = hmac.new(
    b'secret-shared-key-goes-here',
    b'',
    hashlib.sha1,
)

with open('hmac_sha.py', 'rb') as f:
    while True:
        block = f.read(1024)
        if not block:
            break
        digest_maker.update(block)

digest = digest_maker.hexdigest()
print(digest)
```
#### JavaScript
- `addSignature` function
- `checkSignature` function
- `encrypt` should sign the request using `addSignature`
- `decrypt` should check the request using `checkSignature`

_From the JavaScript reference highlighted in additional context:_
```ts
const hmacSHA1 = (key: string, data: string) => {
  // hmac.digest([encoding])
  // If encoding is provided a string is returned; otherwise a Buffer is returned;
  return crypto.createHmac('sha1', key).update(data).digest('hex');
}
```

### TODOs
- [x] js-side signing + concatenation
- [x] js-side validation then decryption
- [x] py-side signing + concatenation
- [x] py-side validation then decryption 
- [ ] document js-side
- [ ] document py-side

### Describe alternatives you've considered

Not doing this. But then what's the point of this lib? I see a big reason for making this super simple is that a lot of data sits in logs at who-knows-where for many of us devs. 

That's a shit sandwich for a variety of reasons and hopefully this lib makes things a bit more simple and seamless.
### Additional context

- [Dotnet CBC vuln overview](https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode)
- [Python HMAC Example](https://pymotw.com/3/hmac/#binary-digests)
- [OSS examples in JavaScript](https://www.tabnine.com/code/javascript/classes/crypto/Hmac)
